
export const PRODUCTS = [
  {
    id: 1,
    ProductName: 'BlackShark V2', 
    Price: 999.0,
    OldPrice: 1050.85,
    ProductImage: '/images/Technology/Headphone1.1.jpg',
    BrandName: 'Razer',  
    value: 'Technology',
    status:"P",
    category:"Technology",
    subcategory: 'Accessory',
    Description: 'Embrace the sound of esports with the Razer BlackShark V2 X. Officially made for PlayStation, experience a triple threat of amazing audio, superior mic clarity and supreme sound isolation. Featuring our best headset mic and audio drivers, your competitive console play is destined to turn pro.',
    img1: '/images/Technology/Headphone1.1.jpg',
    img2: '/images/Technology/Headphone1.2.jpg',
    img3: '/images/Technology/Headphone1.3.jpg',
    img4: '/images/Technology/Headphone1.4.jpg' 
  },
  {
    id: 2,
    ProductName: "HyperX Cloud II",
    Price: 1999.0,
    ProductImage: '/images/Technology/Headphone2.1.jpg',
    BrandName: 'HyperX',  
    OldPrice: 2500,
    value: 'Technology',
    status:"F",
    category: "Technology",
    Description: 'HyperX Cloud II features a newly designed USB sound card audio control box that amplifies audio and voice for an optimal Hi-Fi, gaming experience, so you can hear what you’ve been missing. Open up a world of detail other gamers will never know — the rustle of a camper’s boot, the scuttle in a distant vent. This next generation headset generates virtual 7.1 surround sound with distance and depth to enhance your gaming, movie or music experience. USB surround sound card works only on PC, Mac, and PS4 This headset will work with the Xbox One with headset adapter from Microsoft. It is not supported with the Xbox 360 or PS3.',
    subcategory: 'Accessory',
    img1: '/images/Technology/Headphone2.1.jpg',
    img2: '/images/Technology/Headphone2.2.jpg',
    img3: '/images/Technology/Headphone2.3.jpg',
    img4: '/images/Technology/Headphone2.4.jpg'  
  },
  {
    id: 3,
    ProductName: "HyperX Pulsefire Haste 2 Core Wireless",
    Price: 699.0,
    ProductImage: '/images/Technology/Mouse1.1.jpg',
    BrandName: 'HyperX',  
    OldPrice: 39.85,
    value: 'Technology',
    status:"L",
    category:"Technology",
    Description: 'Step into the world of high-end gaming gear with the HyperX Pulsefire Haste 2 Core Wireless. This economical alternative to the original Pulsefire Haste 2 features a familiar symmetrical shape in a lightweight frame with an operating weight of only 70 grams. Powered by a single AAA battery, this mouse can game via highspeed 2.4GHz connection for up to 100 hours. Or switch to Bluetooth mode for even longer battery life with a reduced polling rate, perfect for casual gaming. Inside you’ll find the HyperX Custom Core Sensor, capable of up to 12,000 DPI with a maximum polling rate of 1,000Hz to execute quick actions and smooth sweeping movements. You can also count on the durable and tactile TTC Gold switches to keep you gaming with a lifespan of up to 20 million clicks. Making those movements easier are the low-friction skates that glide across cloth mouse pads with ease. Connecting to HyperX NGENUITY Software unlocks the full potential of the Pulsefire Haste 2 Core Wireless. There you can quickly reassign vital functions and macros to the 6-button interface, set precise DPI levels for pin-point tracking, adjust the polling rate to fine-tune performance, and even customize RGB lighting and effects to fit your unique style. The Pulsefire Haste 2 Core Wireless is also certified to work with NVIDIA®️ Reflex to optimize end-to-end system latency with compatible monitors.',
    subcategory: 'Accessory',
    img1: '/images/Technology/Mouse1.1.jpg',
    img2: '/images/Technology/Mouse1.2.jpg',
    img3: '/images/Technology/Mouse1.3.jpg',
    img4: '/images/Technology/Mouse1.4.jpg'  
  },
  {
    id: 4,
    ProductName: 'Tiergrade Link Cable 16FT ', 
    Price: 999.0,
    OldPrice: 1050.85,
    ProductImage: '/images/Technology/cable1.3.jpg',
    BrandName: 'Tiergrade',  
    value: 'Technology',
    status:"P",
    category:"Technology",
    Description: 'Tiergrade Link Cable 16FT Compatible with Meta Quest 3/2/Pro, Separate USB-C Charging Cable for Power Supply, USB 3.0 to Type-C for VR Headset/Gaming PC',
    subcategory: 'Accessory',
    img1: '/images/Technology/cable1.1.jpg',
    img2: '/images/Technology/cable1.2.jpg',
    img3: '/images/Technology/cable1.3.jpg',
    img4: '/images/Technology/cable1.4.jpg' 
  },
  {
    id: 5,
    ProductName: 'SAMSUNG Galaxy A35 5', 
    Price: 999.0,
    OldPrice: 1050.85,
    ProductImage: '/images/Technology/SAMSUNG-Galaxy.1.jpg',
    BrandName: 'SAMSUNG Galaxy',  
    value: 'Technology',
    status:"F",
    category:"Technology",
    Description: 'SAMSUNG Galaxy A35 5G A Series Cell Phone, 128GB Unlocked Android Smartphone, AMOLED Display, Advanced Triple Camera System, Expandable Storage, Rugged Design, US Version, 2024, Awesome Navy',
    subcategory: 'Android',
    img1: '/images/Technology/SAMSUNG-Galaxy.1.jpg',
    img2: '/images/Technology/SAMSUNG-Galaxy.2.jpg',
    img3: '/images/Technology/SAMSUNG-Galaxy.3.jpg',
    img4: '/images/Technology/SAMSUNG-Galaxy.4.jpg' 
  },
  {
    id: 6,
    ProductName: 'Oppo Find X5', 
    Price: 999.0,
    OldPrice: 1050.85,
    ProductImage: '/images/Technology/Oppo.1.jpg',
    BrandName: 'Oppo',  
    value: 'Technology',
    status:"L",
    category:"Technology",
    Description: 'Oppo Find X5 CPH2307 Global ROM 8GB + ROM 256GB EU Model Dual SIM Mobile Cell Phone - White',
    subcategory: 'Android',
    img1: '/images/Technology/Oppo.1.jpg',
    img2: '/images/Technology/Oppo.2.jpg',
    img3: '/images/Technology/Oppo.3.jpg',
    img4: '/images/Technology/Oppo.4.jpg' 
  },
  {
    id: 7,
    ProductName: 'Apple iPhone 13 Pro, 128GB, Gold - GSM Carriers (Renewed)', 
    Price: 999.0,
    OldPrice: 1050.85,
    ProductImage: '/images/Technology/iphone.1.jpg',
    BrandName: 'Apple',  
    value: 'Technology',
    status:"P",
    category:"Technology",
    Description: 'Your new superpower. A superbright display in a durable design. Hollywood-worthy video shooting made easy. A lightning-fast chip. And a big boost in battery life youll notice every day.',
    subcategory: 'Iphone',
    img1: '/images/Technology/iphone.1.jpg',
    img2: '/images/Technology/iphone.2.jpg',
    img3: '/images/Technology/iphone.3.jpg',
    img4: '/images/Technology/iphone.4.jpg' 
  },
  {
    id: 8,
    ProductName: 'Dell Inspiron 15', 
    Price: 999.0,
    OldPrice: 1050.85,
    ProductImage: '/images/Technology/laptop.3.jpg',
    BrandName: 'Dell',  
    value: 'Technology',
    status:"F",
    category:"Technology",
    Description: 'Dell Inspiron 15 3000 3520 Business Laptop Computer[Windows 11 Pro], 15.6 FHD Touchscreen, 11th Gen Intel Quad-Core i5-1135G7, 16GB RAM, 1TB',
    subcategory: 'Laptop',
    img1: '/images/Technology/laptop.1.jpg',
    img2: '/images/Technology/laptop.2.jpg',
    img3: '/images/Technology/laptop.3.jpg',
    img4: '/images/Technology/laptop.4.jpg' 
  },
  /////////////////////
  {
    id: 9,
    ProductName: 'Gildan Men s Crew T-Shirts, Multipack, Style G1100', 
    Price: 999.0,
    OldPrice: 1050.85,
    ProductImage: '/images/Fashion/Shirt.1.jpg',
    BrandName: 'Gildan',  
    value: 'Fashion',
    status:"L",
    category:"Fashion",
    Description: 'Gildan Cotton Crew Neck T-Shirts are anything but basic. Crafted with soft, breathable cotton and moisture wicking technology to keep you cool and comfortable no matter whats on the agenda. Perfect for layering or lounging - you can thank us later.',
    subcategory: 'Shirt',
    img1: '/images/Fashion/Shirt.1.jpg',
    img2: '/images/Fashion/Shirt.2.jpg',
    img3: '/images/Fashion/Shirt.3.jpg',
    img4: '/images/Fashion/Shirt.4.jpg' 
  },
  {
    id: 10,
    ProductName: 'IZOD Mens American Chino Flat Front Straight Fit Pant', 
    Price: 999.0,
    OldPrice: 1050.85,
    ProductImage: '/images/Fashion/Pant.1.jpg',
    BrandName: 'IZOD Mens Sportswear',  
    value: 'Fashion',
    status:"F",
    category:"Fashion",
    Description: 'The IZOD American chino trousers are designed for great looks and comfort, whether they re worn in the boardroom, out for a day of golfing, or on a night out. Our straight-fit chino pant combines timeless, classic style with versatility. These mens dress pants deliver all-day comfort and contemporary good looks.',
    subcategory: 'Pant',
    img1: '/images/Fashion/Pant.1.jpg',
    img2: '/images/Fashion/Pant.2.jpg',
    img3: '/images/Fashion/Pant.3.jpg',
    img4: '/images/Fashion/Pant.4.jpg' 
  },
  {
    id:11,
    ProductName: 'Under Armour Men Charged Assert 10', 
    Price: 999.0,
    OldPrice: 1050.85,
    ProductImage: '/images/Fashion/Shoes.1.jpg',
    BrandName: 'Under Armour',  
    value: 'Fashion',
    status:"P",
    category:"Fashion",
    Description: 'Mens UA Charged Assert 10 Running Shoes These are running shoes anyone can wear to go faster—with Charged Cushioning to help protect against impact, a breathable upper, and durability for miles.',
    subcategory: 'Shoe',
    img1: '/images/Fashion/Shoes.1.jpg',
    img2: '/images/Fashion/Shoes.2.jpg',
    img3: '/images/Fashion/Shoes.3.jpg',
    img4: '/images/Fashion/Shoes.4.jpg' 
  },
  {
    id: 12,
    ProductName: 'Apple', 
    Price: 999.0,
    OldPrice: 1050.85,
    ProductImage: '/images/Grocery/Apple.1.jpg',
    BrandName: 'Kauffman',  
    value: 'Grocery',
    status:"L",
    category:"Grocery",
    Description: 'Kauffman Orchards Fresh Mcintosh Apples, Hand-Picked New-Crop Wax-Free Heirloom Macintosh Apples (Box of 16)',
    subcategory: 'Fruit',
    img1: '/images/Grocery/Apple.1.jpg',
    img2: '/images/Grocery/Apple.2.jpg',
    img3: '/images/Grocery/Apple.3.jpg',
    img4: '/images/Grocery/Apple.4.jpg' 
  },
  {
    id: 13,
    ProductName: '', 
    Price: 999.0,
    OldPrice: 1050.85,
    ProductImage: '/images/Grocery',
    BrandName: '',  
    value: '',
    category:"Grocery",
    Description: '',
    subcategory: 'Vegitable',
    img1: '/images/Grocery',
    img2: '/images/Grocery',
    img3: '/images/Grocery',
    img4: '/images/Grocery' 
  },
  {
    id: 14,
    ProductName: '', 
    Price: 999.0,
    OldPrice: 1050.85,
    ProductImage: '/images/Grocery/machine.1.jpg',
    BrandName: 'BLACK+DECKER',  
    value: 'Grocery',
    status:"P",
    category:"Grocery",
    Description: 'BLACK+DECKER PowerCrush Countertop Blender, BL1230SG, 6-Cup Glass Jar, 4 Speed Settings, Dishwasher Safe, 700W Motor',
    subcategory: 'Kitchen',
    img1: '/images/Grocery/machine.1.jpg',
    img2: '/images/Grocery/machine.2.jpg',
    img3: '/images/Grocery/machine.3.jpg',
    img4: '/images/Grocery/machine.4.jpg' 
  },
];
